# What is numpy for exactly?

Numpy is a Python library that bridges the gap between CS "arrays" (or in Python, "lists") into Math ideas of "vectors" and "matrices"... it makes a lot of the things that are easy to do in a language like MATLAB just as easy in Python.

## Quick overview of `list` in Python (skip if already comfortable with lists)

In Python (and most any other programming language) we have objects called "arrays". It's just a list of other objects... in fact "list" is exactly what Python calls a version of it's "arrays" (so the words will be used interchangeably here)... check this out

In [29]:
array = [1,2,3]

print("array = {}, array is object type = {}".format(array, type(array)))

array = [1, 2, 3], array is object type = <class 'list'>


So we just made an array of integers. But if we were being mathy, we could call this a 1 dimensional array a "vector".

Now what do you make of the example below?

In [26]:
array2 = [[1,2,3],[4,5,6]]

print("Our new array = {}".format(array2))

Our new array = [[1, 2, 3], [4, 5, 6]]


Notice the outer brackets... does this look like two arrays engulfed in another array? Because that's exactly what it is!

We can check out the length of an array/list and it's contents to get better intuition like this:

In [23]:
# how many objects in our list?
len(array2)

2

In [27]:
# what's the first object in our list?
array2[0]

[1, 2, 3]

In [28]:
# what's the length of the first object in our list?
len(array2[0])

3

Look at that! our "array2" object is a list of length 2 because it has two objects in it. The first object turned out to also be a list. We can think of this list of lists as a matrix.

So if a list with a single number is a "scalar":

`[3]`

And we can think about a single list with multiple numbers as a "vector":

`vector = [1,2,3]`

Then we can think of a list of lists of multiple numbers as a "matrix":

`matrix = [[1,2,3],[4,5,6]]`

Do you see it? Imagine that the second list was stacked underneath the first list like this:

[1,2,3] <br>
[4,5,6]

Look like a matrix now? OK we're ready to think about numpy now...

## Using numpy arrays instead of Python lists

In [40]:
# before we can start using it, we need to import it
# by convention, numpy is usually imported as `np` to make calling its functions easier

import numpy as np

** Different ways to make a numpy array **

In [36]:
# you can choose all your own values
array1 = np.array([1,4,3,2])

print("array1 = {}".format(array1))
print("array1 has a shape of {}".format(array1.shape))
print("")

# you can add other dimensions to the array
array2 = np.array([[3,2,1],[5,3,4]])
print("array2 = {}".format(array2))
print("array2 has a shape of {}".format(array2.shape))
print("")

# you can just choose the dimensions and make the values all zero
array3 = np.zeros([3,3])
print("array3 = {}".format(array3))
print("array3 has a shape of {}".format(array3.shape))
print("")

# here's another example with 3 dimensions instead of 2
array4 = np.zeros([4,3,2])
print("array4 = {}".format(array4))
print("array4 has a shape of {}".format(array4.shape))

array1 = [1 4 3 2]
array1 has a shape of (4,)

array2 = [[3 2 1]
 [5 3 4]]
array2 has a shape of (2, 3)

array3 = [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
array3 has a shape of (3, 3)

array4 = [[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]
array4 has a shape of (4, 3, 2)


### About "shapes" and terms

The word shape you see thrown around above refers to the _length_ of each dimension in your array/vector/matrix... 

For `array1` we see it is shape (4,) meaning it has 4 columns and only 1 row (computationally there is some difference between `(4,)` and `(4,1)` but for our purposes we'll treat them as the same thing). 

If an object has just 1 row and just 1 column then it is just 1 number... a scalar... like [3]... or [5]...

If an object has just 1 row but multiple columns or if it has multiple rows but just one column then it is a vector... like this

[2,3,4,5]

or

[2, <br>
 3, <br>
 4, <br>
 5]

If an object has multiple rows and columns then it is a matrix... like `array3` and `array4` in the examples above... however notice that the shape for `array4` is (4,3,2)... it has three numbers... this means it has three dimensions. When your dimensions are three or higher, the idea of rows and columns becomes less useful and instead you should think about it as ordinary space... x,y, and z directions... so `array4` goes 4 deep in X direction, 3 deep in Y direction and 2 deep in Z direction. `array4` is still called a matrix.

**Note:** Pay very close attention to where the brackets begin and end in a matrix. Especially in the last example above, do you see all three dimensions in the output of array4? 

## OK I have a numpy array but why is that any different or better than a Python list?

Yup! We've only initialized our matrices and vectors but, with `np.zeros` we saw that we could make matrices of arbitrary dimensions very easily. This is technically possible with basic Python lists but it doesn't look as nice.

For example, what if I want to make a matrix that's shape (3,4,2)... (three dimensions).


In [51]:
# making the three dimensional matrix with just lists
# this uses two "list comprehensions" a.k.a. could be rewritten in more lines of code as two for loops
matrix = [[[0,0] for i in range(4)] for i in range(3)] 
print("Python list-only matrix:")
print(matrix)
print("")
print("The shape of this matrix is ({}, {}, {})".format(len(matrix), len(matrix[0]), len(matrix[0][0])))


print("")

# making the three dimensional matrix with numpy
matrix = np.zeros([3,4,2])
print("Numpy matrix:")
print(matrix)
print("")
print("The shape of this matrix is also {}".format(matrix.shape))

Python list-only matrix:
[[[0, 0], [0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0], [0, 0]]]

The shape of this matrix is (3, 4, 2)

Numpy matrix:
[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]

The shape of this matrix is also (3, 4, 2)


See how much easier and clearer it is with numpy? OK but that's just the surface... of quickly making arrays... yeah basically you're on the surface of the surface... there are a lot of other cool ways like `np.linspace()`. But anyway we'll ignore that for now because what really makes numpy cool is all the mathy operations you can do with your matrices that would require you to write relatively long, complex functions in order to do efficiently without numpy, so let's see that in action!

## The real power of numpy -- mathy manipulations

Here are some basic operations that numpy can perform on vectors/matrices that are very powerful and easy to write.

In [88]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)
print("shape = {}".format(matrix.shape))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape = (3, 3)


In [90]:
print(matrix.T) # transpose the matrix

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [91]:
print(matrix + matrix) # element-wise addition of matrix with itself

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [92]:
print(matrix * matrix) # element-wise multiplication of matrix with itself

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [100]:
print(np.sum(matrix)) # element-wise sum

45


In [96]:
print(np.sum(matrix, axis=1)) # sum across rows

[ 6 15 24]


In [99]:
print(np.sum(matrix, axis=0)) # sum across columns

[12 15 18]


In [102]:
print(np.average(matrix)) # you can use the axis paramater for this too if you want

5.0


In [103]:
np.log(matrix)

array([[ 0.        ,  0.69314718,  1.09861229],
       [ 1.38629436,  1.60943791,  1.79175947],
       [ 1.94591015,  2.07944154,  2.19722458]])

In [104]:
np.random.rand(10) # make random numbers

array([ 0.45987701,  0.94626132,  0.73269401,  0.6832598 ,  0.38347884,
        0.56357137,  0.28978258,  0.45900607,  0.26021896,  0.85282797])

In [107]:
np.linspace(1,10,10) # (start,stop,n) make evenly spaced array

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [108]:
np.arange(10) # range() for a numpy array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

So that's just the beginning really, but that should be more than enough to see how fundamentally important numpy is for Python! Also note that most (if not all?) these functions are vectorized so their use in large data contexts like deep learning becomes all the more important.

## Bonus lesson! Keeping dimensions straight....

When you're doing matrix calculations one of the biggest sources of bugs/errors comes from issues with dimensions. You thought the dimensions were this thing, but they turned out to be something else after one of your steps and that caused an error... I had a professor that recommended you write on paper the dimensions of each variable/matrix before and after dimensions each step of your program before you start to code. This isn't a bad idea, but for starters lets just help you build some intuition about how dimensions change/interact in numpy. 

In each example really pay attention to the dimensions of the matrices/vectors before and after the operation and think if the results make sense to you.

**Matrix x Vector (element-wise multiplication)**

In [58]:
matrix = np.array([[1,2],[3,4]])
vector = np.array([2,3])

result = matrix * vector

print(result)
print("shape = {}".format(result.shape))

[[ 2  6]
 [ 6 12]]
shape = (2, 2)


**Matrix $\cdot$ Vector (dot product)**

In [59]:
matrix = np.array([[1,2],[3,4]])
vector = np.array([2,3])


result = np.dot(matrix,vector) # dot product of matrix and vector

print(result)
print("shape = {}".format(result.shape))

[ 8 18]
shape = (2,)


**Matrix $\cdot$ Matrix (dot product)**

In [60]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

result = np.dot(matrix1,matrix2) # dot product of matrix and matrix

print(result)
print("shape = {}".format(result.shape))

[[19 22]
 [43 50]]
shape = (2, 2)


**Matrix $\cdot$ Matrix$^T$ (dot product)**

In [67]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

result = np.dot(matrix1,matrix2.T) # notice that matrix2 is "transposed"

print("Matrix2 originally:")
print(matrix2)
print("")
print("Matrix2 transposed:")
print(matrix2.T)
print("")
print("np.dot(matrix1,matrix2.T) = ")
print(result)
print("shape = {}".format(result.shape))

Matrix2 originally:
[[5 6]
 [7 8]]

Matrix2 transposed:
[[5 7]
 [6 8]]

np.dot(matrix1,matrix2.T) = 
[[17 23]
 [39 53]]
shape = (2, 2)


**Matrices with different dimensions (dot product)**

In [109]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6,7],[7,8,9]])

result = np.dot(matrix1,matrix2) # do you think this will work?

print("shape of matrix1 = {}".format(matrix1.shape))
print("shape of matrix2 = {}".format(matrix2.shape))
print("")
print("np.dot(matrix1,matrix2) = ")
print(result)
print("shape of this matrix = {}".format(result.shape))

shape of matrix1 = (2, 2)
shape of matrix2 = (2, 3)

np.dot(matrix1,matrix2) = 
[[19 22 25]
 [43 50 57]]
shape of this matrix = (2, 3)


**Pay attention to dimensions!**

In [111]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6,7],[7,8,9]])
matrix2 = matrix2.T # transposed matrix2

try:
    result = np.dot(matrix1,matrix2) # do you think THIS will work???
except:
    print("We couldn't take the dot product! Why not? :( \n")

print("shape of matrix1 = {}".format(matrix1.shape))
print("shape of matrix2 = {}".format(matrix2.shape))

shape of matrix1 = (2, 2)
shape of matrix2 = (2, 3)


**Why does this one work but the previous example doesn't?**

In [98]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6,7],[7,8,9]])
matrix2 = matrix2.T

result = np.dot(matrix2,matrix1) # we switched the order

print("shape of matrix1 = {}".format(matrix1.shape))
print("shape of matrix2 = {}".format(matrix2.shape))
print("")
print("np.dot(matrix2,matrix1) = ") 
print(result)
print("shape of this matrix = {}".format(result.shape))

shape of matrix1 = (2, 2)
shape of matrix2 = (3, 2)

np.dot(matrix1,matrix2) = 
[[26 38]
 [30 44]
 [34 50]]
shape of this matrix = (3, 2)


Hopefully all this seemed clear to you! If not, mess around with the code to try different things out!

### That's it for this tutorial!

You now have a pretty solid start on how to use numpy and what it can do for you... there's obviously a lot more though so always a great idea to check out the <a href="https://docs.scipy.org/doc/numpy-1.14.0/reference/">documentation</a> if you're curious. 